/*
* DO NOT EDIT THIS FILE MANNUALLY.
*
*
* Header file generated AUTOMATICALLY by The batch file ...\Tools\win\makePDFLHfromASF.bat.
* The batch file calls ZBFGen2, a ZString2.0 library program, using the template ...\Tools\win\ztrings\PDFLError_Str.tmpl.
*
* DO NOT EDIT THIS FILE MANNUALLY. THIS IS CLOSELY TIED WITH THE ZString2.0 Binary
* Format. Regenerate this whenever the corresponding .asfx file changes.
*
*/


DefineErr(asFileErrNoErr, "No error.")

DefineErr(asFileErrGeneral, "A file error has occurred.")

DefineErr(asFileErrObsolete, "")

DefineErr(asFileErrDirFull, "The folder is full.")

DefineErr(asFileErrDiskFull, "The disk you were saving to or the disk used for temporary files is full. Free some space on this disk and try again, or save to a different disk.")

DefineErr(asFileErrNSV, "The disk containing this file is not available.")

DefineErr(asFileErrIO, "A file I/O error has occurred.")

DefineErr(asFileErrRead, "A file read error has occurred.")

DefineErr(asFileErrWrite, "A file write error has occurred.")

DefineErr(asFileErrEOF, "End of file was reached unexpectedly.")

DefineErr(asFileErrLocked, "This file is locked.")

DefineErr(asFileErrVLocked, "This disk is locked and cannot be written to.")

DefineErr(asFileErrBusy, "This file is busy and cannot be deleted.")

DefineErr(asFileErrExists, "Another file already exists under the same name.")

DefineErr(asFileErrAlreadyOpen, "This file is already open or in use by another application.")

DefineErr(asFileErrPerm, "You do not have access to this file.")

DefineErr(asFileErrWrPerm, "You do not have permission to write to this file.")

DefineErr(asFileErrFNF, "This file cannot be found.")

DefineErr(asFileErrOpenFailed, "File open failed.")

DefineErr(asFileErrBytesNotReady, "Bytes not ready.")

DefineErr(asFileErrUserRequestedStop, "User requested stop.")

DefineErr(asFileErrIOTimeout, "A file I/O error has occurred. The file connection timed out.")

DefineErr(asFileErrReadBlocked, "A file I/O error has occurred. The file is blocked while reading.")

DefineErr(asFileErrNotADir, "This operation can only be performed on a folder.")

DefineErr(asFileErrTempCreate, "A uniquely named temporary file could not be created. Please restart the application and try again.")

DefineErr(asFileErrTooBig, "This file is too big for the current operation.")



/* End of automatic generated header file */

/***** End of file ***********************************************************/
