/*
* DO NOT EDIT THIS FILE MANNUALLY.
*
*
* Header file generated AUTOMATICALLY by The batch file ...\Tools\win\makePDFLHfromASF.bat.
* The batch file calls ZBFGen2, a ZString2.0 library program, using the template ...\Tools\win\ztrings\PDFLError_Str.tmpl.
*
* DO NOT EDIT THIS FILE MANNUALLY. THIS IS CLOSELY TIED WITH THE ZString2.0 Binary
* Format. Regenerate this whenever the corresponding .asfx file changes.
*
*/


DefineErr(asGenErrNoError, "No error.")

DefineErr(asGenErrGeneral, "An internal error occurred.")

DefineErr(asGenErrNoMemory, "Out of memory.")

DefineErr(asGenErrBadParm, "Bad parameter.")

DefineErr(asGenErrListOverflow, "Operation or data is too complex.")

DefineErr(asGenErrBadUnlock, "Attempt to release an unlocked object.")

DefineErr(asGenErrExceptionStackOverflow, "Exception stack overflow.")

DefineErr(asGenErrResourceLoadFailed, "Failed to load an application resource (internal error).")

DefineErr(asGenErrNameAlreadyRegistered, "Attempt to register an object with a name already in use.")

DefineErr(asGenErrMethodNotImplemented, "Attempt to call a method that has not been implemented.")

DefineErr(asGenErrCanceled, "User canceled operation.")

DefineErr(asGenErrNoValidSerialNoFound, "No valid Acrobat serial number found. Acrobat will now quit.")

DefineErr(asGenErrOutOfRange, "A number is out of range.")



/* End of automatic generated header file */

/***** End of file ***********************************************************/
