/*
* DO NOT EDIT THIS FILE MANNUALLY.
*
*
* Header file generated AUTOMATICALLY by The batch file ...\Tools\win\makePDFLHfromASF.bat.
* The batch file calls ZBFGen2, a ZString2.0 library program, using the template ...\Tools\win\ztrings\PDFLError_Str.tmpl.
*
* DO NOT EDIT THIS FILE MANNUALLY. THIS IS CLOSELY TIED WITH THE ZString2.0 Binary
* Format. Regenerate this whenever the corresponding .asfx file changes.
*
*/


DefineErr(cosErrNoError, "No error")

DefineErr(cosErrReadError, "Read error.")

DefineErr(cosErrWriteError, "Write error.")

DefineErr(cosErrBadSyntax, "Syntax error.")

DefineErr(cosErrNeedRebuild, "The file needs to be repaired.")

DefineErr(cosErrRebuildFailed, "The file is damaged and could not be repaired.")

DefineErr(cosErrCantOpenTempFile, "A temporary file could not be opened.")

DefineErr(cosErrTempFileFull, "The temporary file is full or nearly full. Close or save any modified documents.")

DefineErr(cosErrStreamTooShort, "Stream source is shorter than specified length.")

DefineErr(cosErrBadFilterName, "A stream specifies an unknown filter.")

DefineErr(cosErrListOverflow, "Operation or data is too complex.")

DefineErr(cosErrDocTableFull, "Cos document table full.")

DefineErr(cosErrInt16OutOfRange, "A number is out of range.")

DefineErr(cosErrExpectedNull, "Expected a null object.")

DefineErr(cosErrExpectedDict, "Expected a dict object.")

DefineErr(cosErrExpectedArray, "Expected an array object.")

DefineErr(cosErrExpectedNumber, "Expected a number object.")

DefineErr(cosErrExpectedBoolean, "Expected a boolean object.")

DefineErr(cosErrExpectedName, "Expected a name object.")

DefineErr(cosErrExpectedString, "Expected a string object.")

DefineErr(cosErrExpectedStream, "Expected a stream object.")

DefineErr(cosErrInvalidAssignment, "This direct object already has a container.")

DefineErr(cosErrAfterSave, "Implementation failure: this document is now invalid.")

DefineErr(cosErrInvalidObj, "Desired operation cannot be performed on this object.")

DefineErr(cosErrArrayBounds, "Array out-of-bounds error.")

DefineErr(cosErrDictKeyNotName, "Dict key must be a name object.")

DefineErr(cosErrNeedFullSave, "This file must be saved with a full save.")

DefineErr(cosErrEncryptionErr, "Error in encryption filter.")

DefineErr(cosErrDCTError, "Error in JPEG data filter.")

DefineErr(cosErrCCFError, "Error in CCITT fax data filter.")

DefineErr(cosErrLZWError, "Error in LZW data filter.")

DefineErr(cosErrFlateError, "Error in Flate data filter.")

DefineErr(cosErrExpectedDirect, "Expected a direct object.")

DefineErr(cosErrBadIndex, "Bad master index.")

DefineErr(cosErrOldLinFormat, "Obsolete format: treating file as non-linearized")

DefineErr(cosErrTempTooShort, "Temp file unexpectedly short.")

DefineErr(cosErrCancelSave, "The Save operation was cancelled.")

DefineErr(cosErrEncryptionNotSupported, "Encryption and decryption are not supported.")

DefineErr(cosErrNoEncryptionKeySupplied, "Encryption key is not supplied for a stream.")

DefineErr(cosErrDuplicateFilterName, "A filter with the same name is already registered.")

DefineErr(cosErrNoDecodeFilter, "Attempted to decode without associated filter.")

DefineErr(cosErrNoEncodeFilter, "Attempted to encode without associated filter.")

DefineErr(cosErrCryptAuthFailed, "Decryption authorization failed during data access.")

DefineErr(cosErrExpectedObjectStream, "Expected an object stream.")

DefineErr(cosErrExpectedIndirect, "Expected an indirect object.")

DefineErr(cosErrExpectedProc, "Expected a procedure.")

DefineErr(cosErrExpectedCollection, "Expected an object collection.")

DefineErr(cosErrNotCompressed, "Expected a compressed object.")

DefineErr(cosErrCompressed, "Expected an object that was not compressed.")

DefineErr(cosMsgCopyngFile, "Copying file")

DefineErr(cosMsgLinSave, "Saving for Fast Web Viewing")

DefineErr(cosMsgIncrSave, "Updating file")

DefineErr(cosMsgSavingFile, "Saving file")

DefineErr(cosErrBadRefcount, "An acquired object was already released.")

DefineErr(cosErrObjFreed, "An object has been replaced or destroyed.")

DefineErr(cosErrMemMgrError, "Internal error in the memory manager.")

DefineErr(cosErrNeedXrefStm, "This file requires a cross-reference stream (PDF 1.5)")

DefineErr(cosErrCryptSystem, "Cryptographic system general failure.")


/* End of automatic generated header file */

/***** End of file ***********************************************************/
