/*
* DO NOT EDIT THIS FILE MANNUALLY.
*
*
* Header file generated AUTOMATICALLY by The batch file ...\Tools\win\makePDFLHfromASF.bat.
* The batch file calls ZBFGen2, a ZString2.0 library program, using the template ...\Tools\win\ztrings\PDFLError_Str.tmpl.
*
* DO NOT EDIT THIS FILE MANNUALLY. THIS IS CLOSELY TIED WITH THE ZString2.0 Binary
* Format. Regenerate this whenever the corresponding .asfx file changes.
*
*/


DefineErr(cosSynErrNoError, "No syntax error.")

DefineErr(cosSynErrNoHeader, "File does not begin with '%PDF-'.")

DefineErr(cosSynErrNoEOF, "Missing %%EOF.")

DefineErr(cosSynErrNoStartXRef, "Could not find startxref address.")

DefineErr(cosSynErrNoStartAddress, "Value of startxref address not an integer.")

DefineErr(cosSynErrBadXref, "Missing 'xref'.")

DefineErr(cosSynErrBadXrefHeader, "Xref header should be two integers.")

DefineErr(cosSynErrBadXrefEntry, "Error reading xref entry.")

DefineErr(cosSynErrBadTrailerStart, "Trailer dictionary start missing '<<'.")

DefineErr(cosSynErrBadObjectLabel, "Object label badly formatted.")

DefineErr(cosSynErrUnknownName, "Unrecognized object name.")

DefineErr(cosSynErrUnknownTokenType, "Unrecognized token type.")

DefineErr(cosSynErrNoEndStream, "Missing endstream.")

DefineErr(cosSynErrExtraEndStream, "Unexpected endstream.")

DefineErr(cosSynErrUnterminatedString, "Unterminated string.")

DefineErr(cosSynErrStringTooLong, "String too long.")

DefineErr(cosSynErrTokenTooLong, "Token too long.")

DefineErr(cosSynErrBadCharInHexString, "Non-hex character in a hex string.")

DefineErr(cosSynErrUnexpectedType, "Unexpected token type.")

DefineErr(cosSynErrImageNeverEnded, "End of image not found.")

DefineErr(cosSynErrUnexpectedDict, "Unexpected end of dictionary.")

DefineErr(cosSynErrUnexpectedArray, "Unexpected end of array.")

DefineErr(cosSynErrBadDict, "Error reading dictionary.")

DefineErr(cosSynErrBadObject, "Error reading object.")

DefineErr(cosSynErrBadArrayDict, "Expected dictionary or array.")

DefineErr(cosSynErrBadFRef, "Bad foreign object reference.")

DefineErr(cosSynErrPStackUnderflow, "Parse stack underflow while reading object.")

DefineErr(cosSynErrBadLinearized, "Error reading linearized hint data")

DefineErr(cosSynErrBadHexCharInName, "Non-hex character after # in a name.")

DefineErr(cosSynErrBadName, "Illegal characters in a name.")

DefineErr(cosSynErrBadObjectRef, "An object reference is invalid.")

DefineErr(cosSynErrBadXrefStream, "Error in XRef stream.")

DefineErr(cosSynErrPrematureEOF, "Unexpected end of file.")

DefineErr(cosSynErrBadStreamStart, "Expected CR and/or LF after 'stream'.")

DefineErr(cosSynErrBadObjStream, "Error in object stream.")

DefineErr(cosSynErrDictKeyNotName, "Dictionary keys must be direct name objects.")

DefineErr(cosSynErrExpectedNull, "Expected the null object.")

DefineErr(cosSynErrExpectedNumber, "Expected a number.")

DefineErr(cosSynErrExpectedInteger, "Expected an integer.")

DefineErr(cosSynErrExpectedReal, "Expected a real number.")

DefineErr(cosSynErrExpectedUnsigned, "Expected a non-negative integer.")

DefineErr(cosSynErrExpectedBoolean, "Expected true or false.")

DefineErr(cosSynErrExpectedName, "Expected a name.")

DefineErr(cosSynErrExpectedString, "Expected a string.")

DefineErr(cosSynErrExpectedDict, "Expected a dictionary.")

DefineErr(cosSynErrExpectedArray, "Expected an array.")

DefineErr(cosSynErrExpectedStream, "Expected a stream.")

DefineErr(cosSynErrIllegalStream, "Stream found in an illegal context.")

DefineErr(cosSynErrNoLength, "Stream is missing a Length key.")

DefineErr(cosSynErrExpectedIndirect, "Expected an indirect object")

DefineErr(cosSynErrExpectedDirect, "Expected a direct object")

DefineErr(cosSynErrIllegalIndRef, "Illegal indirect reference")



/* End of automatic generated header file */

/***** End of file ***********************************************************/
