/*
* DO NOT EDIT THIS FILE MANNUALLY.
*
*
* Header file generated AUTOMATICALLY by The batch file ...\Tools\win\makePDFLHfromASF.bat.
* The batch file calls ZBFGen2, a ZString2.0 library program, using the template ...\Tools\win\ztrings\PDFLError_Str.tmpl.
*
* DO NOT EDIT THIS FILE MANNUALLY. THIS IS CLOSELY TIED WITH THE ZString2.0 Binary
* Format. Regenerate this whenever the corresponding .asfx file changes.
*
*/


DefineErr(fsErrNoError, "No error.")

DefineErr(fsErrInitFailed, "Initialization of the font server module failed.")

DefineErr(fsErrNoMMFonts, "No Multiple Master fonts were found.")

DefineErr(fsErrNoATM, "Adobe Type Manager was not found.")

DefineErr(fsErrNeedNewATM, "A new version of Adobe Type Manager is required.")

DefineErr(fsErrNoT1ZapfDingbats, "The Type 1 font 'ZapfDingbats' must be installed.")

DefineErr(fsErrDownloadFailed, "Font download failed.")

DefineErr(fsErrDownloadAborted, "Font download aborted.")

DefineErr(fsErrBadParameter, "Bad parameter passed to font server.")

DefineErr(fsErrMissingFont, "No ZapfDingbats or Multiple Master fonts found.")



/* End of automatic generated header file */

/***** End of file ***********************************************************/
