/*
* DO NOT EDIT THIS FILE MANNUALLY.
*
*
* Header file generated AUTOMATICALLY by The batch file ...\Tools\win\makePDFLHfromASF.bat.
* The batch file calls ZBFGen2, a ZString2.0 library program, using the template ...\Tools\win\ztrings\PDFLError_Str.tmpl.
*
* DO NOT EDIT THIS FILE MANNUALLY. THIS IS CLOSELY TIED WITH THE ZString2.0 Binary
* Format. Regenerate this whenever the corresponding .asfx file changes.
*
*/


DefineErr(pdfxErrNoError, "No error.")

DefineErr(pdfxErrWrongCallbacks, "The size of the passed callbacks struct is wrong.")

DefineErr(pdfxErrDuringCallback, "Tried to call a PDFXInstance function during a callback proc.")

DefineErr(pdfxErrCannotLaunchAcrobat, "PDFX could not launch Acrobat.")

DefineErr(pdfxErrCannotFindEWH, "Could not find the External Window Handler plug-in.")



/* End of automatic generated header file */

/***** End of file ***********************************************************/
