/*
* DO NOT EDIT THIS FILE MANNUALLY.
*
*
* Header file generated AUTOMATICALLY by The batch file ...\Tools\win\makePDFLHfromASF.bat.
* The batch file calls ZBFGen2, a ZString2.0 library program, using the template ...\Tools\win\ztrings\PDFLError_Str.tmpl.
*
* DO NOT EDIT THIS FILE MANNUALLY. THIS IS CLOSELY TIED WITH THE ZString2.0 Binary
* Format. Regenerate this whenever the corresponding .asfx file changes.
*
*/


DefineErr(pdMetadataErrBadXAP, "The given metadata was not in the XMP format")

DefineErr(pdMetadataErrBadPDF, "XMP metadata processing found a syntax error in PDF")

DefineErr(pdMetadataErrCouldntCreateMetaXAP, "Could not create internal representation of XMP metadata")

DefineErr(pdMetadataErrInternalError, "An internal error occurred while processing XMP metadata")



/* End of automatic generated header file */

/***** End of file ***********************************************************/
