/*
* DO NOT EDIT THIS FILE MANNUALLY.
*
*
* Header file generated AUTOMATICALLY by The batch file ...\Tools\win\makePDFLHfromASF.bat.
* The batch file calls ZBFGen2, a ZString2.0 library program, using the template ...\Tools\win\ztrings\PDFLError_Str.tmpl.
*
* DO NOT EDIT THIS FILE MANNUALLY. THIS IS CLOSELY TIED WITH THE ZString2.0 Binary
* Format. Regenerate this whenever the corresponding .asfx file changes.
*
*/


DefineErr(pdModErrNoError, "No error.")

DefineErr(pdModErrEncTablesFailed, "Unable to initialize font encoding tables.")

DefineErr(pdModErrDuplicateCryptName, "A security plug-in is already registered with this name.")

DefineErr(pdModErrDuplicatePermName, "A permission handler is already registered with this name.")

DefineErr(pdModErrBadNavigator, "This navigator file cannot be read.  Ensure that the mimetype file exists and is the first file in the package.")

DefineErr(pdModErrNewNavigator, "This navigator requires a new version of Acrobat.")

DefineErr(pdModErrNavUnknownExtension, "This navigator does not have a valid file extension. The only valid file extension for a navigator is either \"nav\" or \"swf\".")

DefineErr(pdModErrNavInvalidMimeType, "This navigator has an invalid mimetype file. The navigator mimetype must be \"application/vnd.adobe.pdf-navigator\".")

DefineErr(pdModErrNavMissingSwf, "This navigator is missing its swf file. Check the spelling of the file name (it is case sensitive).")

DefineErr(pdModErrNavMissingNavigatorXML, "This navigator is missing its navigator xml file.")

DefineErr(pdModErrNavMissingLocalesXML, "This navigator is missing its locales xml file. Check the spelling of the file name (it is case sensitive).")

DefineErr(pdModErrNavMissingStringsXML, "This navigator is missing one or more of its localization xml files. Check the spelling of the file name (it is case sensitive).")

DefineErr(pdModErrNavInvalidNavigatorXML, "This navigator's navigator xml file is malformed. Verify that your xml file is valid per the navigator schema.")

DefineErr(pdModErrNavInvalidLocalesXML, "This navigator's locales xml file is malformed. Verify that your xml file is valid per the navigator schema.")

DefineErr(pdModErrNavInvalidStringsXML, "One or more of this navigator's localization xml files is malformed. Verify that your xml file is valid per the navigator schema.")



/* End of automatic generated header file */

/***** End of file ***********************************************************/
