/*
* DO NOT EDIT THIS FILE MANNUALLY.
*
*
* Header file generated AUTOMATICALLY by The batch file ...\Tools\win\makePDFLHfromASF.bat.
* The batch file calls ZBFGen2, a ZString2.0 library program, using the template ...\Tools\win\ztrings\PDFLError_Str.tmpl.
*
* DO NOT EDIT THIS FILE MANNUALLY. THIS IS CLOSELY TIED WITH THE ZString2.0 Binary
* Format. Regenerate this whenever the corresponding .asfx file changes.
*
*/


DefineErr(pdPErrNoError, "No error.")

DefineErr(pdPErrPageDimOutOfRange, "The dimensions of this page are out-of-range.")

DefineErr(pdPErrBadType3Font, "Invalid Type 3 font.")

DefineErr(pdPErrType3TooComplex, "Type 3 font is too complex to print.")

DefineErr(pdPErrFormTooComplex, "Form is too complex to print.")

DefineErr(pdPErrUnableToCreateRasterPort, "Creation of a raster port failed.")



/* End of automatic generated header file */

/***** End of file ***********************************************************/
