/*
* DO NOT EDIT THIS FILE MANNUALLY.
*
*
* Header file generated AUTOMATICALLY by The batch file ...\Tools\win\makePDFLHfromASF.bat.
* The batch file calls ZBFGen2, a ZString2.0 library program, using the template ...\Tools\win\ztrings\PDFLError_Str.tmpl.
*
* DO NOT EDIT THIS FILE MANNUALLY. THIS IS CLOSELY TIED WITH THE ZString2.0 Binary
* Format. Regenerate this whenever the corresponding .asfx file changes.
*
*/


DefineErr(pdsErrRequiredMissing, "A required field was missing from a dictionary")

DefineErr(pdsErrBadPDF, "An incorrect structure was found in the PDF file")

DefineErr(pdsErrWrongTypeEntry, "Dictionary entry has wrong Cos type")

DefineErr(pdsErrWrongTypeParameter, "Wrong type parameter supplied to a PDS procedure")

DefineErr(pdsErrAlreadyExists, "There is already a table entry with the same name")

DefineErr(pdsErrCantDo, "Some software required to perform this operation is not present in this version of Adobe Acrobat")



/* End of automatic generated header file */

/***** End of file ***********************************************************/
