/*
* DO NOT EDIT THIS FILE MANNUALLY.
*
*
* Header file generated AUTOMATICALLY by The batch file ...\Tools\win\makePDFLHfromASF.bat.
* The batch file calls ZBFGen2, a ZString2.0 library program, using the template ...\Tools\win\ztrings\PDFLError_Str.tmpl.
*
* DO NOT EDIT THIS FILE MANNUALLY. THIS IS CLOSELY TIED WITH THE ZString2.0 Binary
* Format. Regenerate this whenever the corresponding .asfx file changes.
*
*/


DefineErr(peErrNoError, "No error")

DefineErr(peErrUnknownPDEColorSpace, "Unknown PDEColorSpace value.")

DefineErr(peErrWrongPDEObjectType, "Incorrect PDEObject type.")

DefineErr(peErrUnknownResType, "Unknown PDEObject resource type.")

DefineErr(peErrPStackUnderflow, "PDFEdit parse stack underflow while reading object.")

DefineErr(peErrCantCreateFontSubset, "Unable to create embedded font subset.")

DefineErr(peErrBadBlockHeader, "Bad block header for type 1 embedded stream.")

DefineErr(peErrCantGetAttrs, "Unable to get attributes for font.")

DefineErr(peErrCantGetWidths, "Unable to get widths for font.")

DefineErr(peErrFontToEmbedNotOnSys, "Unable to find font to embed on this system.")

DefineErr(peErrCantEmbedFont, "This font is licensed and cannot be embedded.")

DefineErr(peErrCantGetImageDict, "Unable to get image dictionary.")

DefineErr(peErrCantReadImage, "Unable to read image data.")

DefineErr(peErrCantGetShading, "Unable to get shading resource.")

DefineErr(peErrWrongOpType, "Wrong operand type.")

DefineErr(peErrTooFewPathOps, "Too few operands in path.")

DefineErr(peErrErrorParsingImage, "There was an error while trying to parse an image.")

DefineErr(peErrReadLessImageColor, "Read less image color data than expected.")

DefineErr(peErrReadLessImageData, "Read less image data than expected.")

DefineErr(peErrBadResMetrics, "Invalid or corrupt font metrics in the resource file.")

DefineErr(peErrBadType3Font, "Invalid Type 3 font.")

DefineErr(peErrInvalidUnicodeAttribute, "Invalid Unicode attribute or attribute not set.")

DefineErr(peErrIllegalUTFText, "Invalid Unicode text.")



/* End of automatic generated header file */

/***** End of file ***********************************************************/
