/*
* DO NOT EDIT THIS FILE MANNUALLY.
*
*
* Header file generated AUTOMATICALLY by The batch file ...\Tools\win\makePDFLHfromASF.bat.
* The batch file calls ZBFGen2, a ZString2.0 library program, using the template ...\Tools\win\ztrings\PDFLError_Str.tmpl.
*
* DO NOT EDIT THIS FILE MANNUALLY. THIS IS CLOSELY TIED WITH THE ZString2.0 Binary
* Format. Regenerate this whenever the corresponding .asfx file changes.
*
*/


DefineErr(rasErrNoError, "No error.")

DefineErr(rasErrInitFailed, "Initialization of the rasterizer module failed.")

DefineErr(rasErrCreatePort, "Creation of rasterizer port failed.")

DefineErr(rasErrDraw, "A drawing error occurred.")

DefineErr(rasErrGPUFailed, "GPU drawing failed; reverted to CPU.")



/* End of automatic generated header file */

/***** End of file ***********************************************************/
