/*
* DO NOT EDIT THIS FILE MANNUALLY.
*
*
* Header file generated AUTOMATICALLY by The batch file ...\Tools\win\makePDFLHfromASF.bat.
* The batch file calls ZBFGen2, a ZString2.0 library program, using the template ...\Tools\win\ztrings\PDFLError_Str.tmpl.
*
* DO NOT EDIT THIS FILE MANNUALLY. THIS IS CLOSELY TIED WITH THE ZString2.0 Binary
* Format. Regenerate this whenever the corresponding .asfx file changes.
*
*/


DefineErr(xmErrNoError, "No error.")

DefineErr(xmErrOutOfDateHFT, "The plug-in was compiled with an out-of-date HFT.")

DefineErr(xmErrNoPLUGResource, "The plug-in appears to be damaged or in use.")

DefineErr(xmErrPlugInIncompatible, "The plug-in is incompatible with this version of the Acrobat.")

DefineErr(xmErrInitializationFailed, "The plug-in failed to initialize.")

DefineErr(xmErrDuplicatePlugInName, "Two plug-ins are attempting to register with the same name.")

DefineErr(xmErrCannotReplaceSelector, "Attempt to replace an unreplaceable selector.")

DefineErr(xmErrCalledObsoleteProc, "An unimplemented or obsolete function was called.")

DefineErr(xmErrPlugInLoadFailed, "The plug-in failed to load.")

DefineErr(xmErrNotPrivileged, "The Adobe Reader cannot load this plug-in.")

DefineErr(xmErr68KOnly, "Only the 68K Viewer can load this plug-in.")

DefineErr(xmErrPPCOnly, "Only the PowerPC Viewer can load this plug-in.")

DefineErr(xmErrPlugInNotTrusted, "This is not a trusted plug-in.")

DefineErr(xmErrPlugInNotCarbonized, "This plugin cannot load on MacOS X.")

DefineErr(xmErrPluginResourceMismatch, "The currently selected language resources are not supported by this plugin.")



/* End of automatic generated header file */

/***** End of file ***********************************************************/
